name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:

jobs:
  auto_assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Reviewer
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign.yml' # Only needed if you use something other than .github/auto_assign.yml
  slack_notification:
    runs-on: ubuntu-latest
    needs: auto_assign_reviewer
    steps:
      - name: Slack Notification
        run: |
          echo "Slack notification"
          echo "REPOSITORY >> ${{ toJson(github.repository) }}"
          echo "Events >> ${{ toJson(github.event) }}"
          echo "PULL REQUEST >> ${{ toJson(github.event.pull_request) }}"
          
