name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review, edited]

jobs:
  auto_assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Reviewer
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-assign.yml' # Only needed if you use something other than .github/auto_assign.yml