name: Send Slack Notifications for Open PRs

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: pull-request-test
          status: SUCCESS
          color: good
      
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: pull-request-test
          status: FAILED
          color: danger