name: Send Slack Notifications for Open PRs

on:
  pull_request:
    types: [opened]

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_channel: "pull-request-test"
          slack_message: "Novo Pull Request aberto: ${{ github.event.pull_request.title }}\n${{ github.event.pull_request.html_url }}"
        env:
          SLACK_BOT_USER_OAUTH_ACCESS_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}